##################################################
# Default makefile
# Redirect make to target makefile
##################################################

all:
	make -f MakefileCar.mk all
clean:
	make -f MakefileCar.mk clean
.PHONY: 
	make -f MakefileCar.mk all clean
