##################################################
# Default makefile
# Redirect make to target makefile
##################################################

all:
	make -f MakefileSimulator.mk all
clean:
	make -f MakefileSimulator.mk clean
.PHONY: 
	make -f MakefileSimulator.mk all clean
