
#include "SimulatorControllers.hh"

#include "Client.hh"
#include "ENV.hh"
#include "Server.hh"
#include "Simulator.hh"
#include "umlrtcapsuleclass.hh"
#include "umlrtcapsulepart.hh"
#include "umlrtcommsport.hh"
#include "umlrtcommsportfarend.hh"
#include "umlrtcontroller.hh"
#include "umlrtslot.hh"
#include <cstddef>


static UMLRTController DefaultController_( "DefaultController" );

UMLRTController * DefaultController = &DefaultController_;

static Capsule_Simulator simulator( &Simulator, &Simulator_slots[InstId_Simulator], NULL, NULL, true );

static UMLRTSlot * slots_Simulator[] = 
{
    &Simulator_slots[InstId_Simulator_ENV],
    &Simulator_slots[InstId_Simulator_client_0],
    &Simulator_slots[InstId_Simulator_client_1],
    &Simulator_slots[InstId_Simulator_client_2],
    &Simulator_slots[InstId_Simulator_client_3],
    &Simulator_slots[InstId_Simulator_client_4],
    &Simulator_slots[InstId_Simulator_server1],
    &Simulator_slots[InstId_Simulator_server2]
};

static UMLRTCapsulePart parts_Simulator[] = 
{
    {
        &Simulator,
        Capsule_Simulator::part_ENV,
        1,
        &slots_Simulator[0]
    },
    {
        &Simulator,
        Capsule_Simulator::part_client,
        5,
        &slots_Simulator[1]
    },
    {
        &Simulator,
        Capsule_Simulator::part_server1,
        1,
        &slots_Simulator[6]
    },
    {
        &Simulator,
        Capsule_Simulator::part_server2,
        1,
        &slots_Simulator[7]
    }
};

static UMLRTCommsPortFarEnd borderfarEndList_Simulator_ENV[] = 
{
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    }
};

UMLRTCommsPort borderports_Simulator_ENV[] = 
{
    {
        &ENV,
        Capsule_ENV::borderport_AnnouncmentServer1,
        &Simulator_slots[InstId_Simulator_ENV],
        1,
        borderfarEndList_Simulator_ENV,
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false
    },
    {
        &ENV,
        Capsule_ENV::borderport_AnnouncmentServer2,
        &Simulator_slots[InstId_Simulator_ENV],
        1,
        &borderfarEndList_Simulator_ENV[1],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false
    },
    {
        &ENV,
        Capsule_ENV::borderport_BITTimer,
        &Simulator_slots[InstId_Simulator_ENV],
        1,
        &borderfarEndList_Simulator_ENV[2],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false
    },
    {
        &ENV,
        Capsule_ENV::borderport_ConfigComm,
        &Simulator_slots[InstId_Simulator_ENV],
        7,
        &borderfarEndList_Simulator_ENV[3],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false
    },
    {
        &ENV,
        Capsule_ENV::borderport_FailureTimer,
        &Simulator_slots[InstId_Simulator_ENV],
        1,
        &borderfarEndList_Simulator_ENV[10],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false
    },
    {
        &ENV,
        Capsule_ENV::borderport_GeneralTimer,
        &Simulator_slots[InstId_Simulator_ENV],
        1,
        &borderfarEndList_Simulator_ENV[11],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false
    },
    {
        &ENV,
        Capsule_ENV::borderport_configTimer,
        &Simulator_slots[InstId_Simulator_ENV],
        1,
        &borderfarEndList_Simulator_ENV[12],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false
    }
};

static const UMLRTCommsPort * borderports_Simulator_ENV_ptrs[] = 
{
    &borderports_Simulator_ENV[0],
    &borderports_Simulator_ENV[1],
    &borderports_Simulator_ENV[2],
    &borderports_Simulator_ENV[3],
    &borderports_Simulator_ENV[4],
    &borderports_Simulator_ENV[5],
    &borderports_Simulator_ENV[6]
};

static Capsule_ENV simulator_ENV( &ENV, &Simulator_slots[InstId_Simulator_ENV], borderports_Simulator_ENV_ptrs, NULL, true );

static UMLRTCommsPortFarEnd borderfarEndList_Simulator_client_0[] = 
{
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        &borderports_Simulator_server1[Capsule_Server::borderport_ServerComm]
    },
    {
        0,
        &borderports_Simulator_server2[Capsule_Server::borderport_ServerComm]
    },
    {
        0,
        NULL
    }
};

UMLRTCommsPort borderports_Simulator_client_0[] = 
{
    {
        &Client,
        Capsule_Client::borderport_ConfigComm,
        &Simulator_slots[InstId_Simulator_client_0],
        1,
        borderfarEndList_Simulator_client_0,
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false
    },
    {
        &Client,
        Capsule_Client::borderport_ConfigTimer,
        &Simulator_slots[InstId_Simulator_client_0],
        1,
        &borderfarEndList_Simulator_client_0[1],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false
    },
    {
        &Client,
        Capsule_Client::borderport_RequestTimer,
        &Simulator_slots[InstId_Simulator_client_0],
        1,
        &borderfarEndList_Simulator_client_0[2],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false
    },
    {
        &Client,
        Capsule_Client::borderport_ResponseTimer,
        &Simulator_slots[InstId_Simulator_client_0],
        1,
        &borderfarEndList_Simulator_client_0[3],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false
    },
    {
        &Client,
        Capsule_Client::borderport_Server1Comm,
        &Simulator_slots[InstId_Simulator_client_0],
        1,
        &borderfarEndList_Simulator_client_0[4],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true
    },
    {
        &Client,
        Capsule_Client::borderport_Server2Comm,
        &Simulator_slots[InstId_Simulator_client_0],
        1,
        &borderfarEndList_Simulator_client_0[5],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true
    },
    {
        &Client,
        Capsule_Client::borderport_Timer,
        &Simulator_slots[InstId_Simulator_client_0],
        1,
        &borderfarEndList_Simulator_client_0[6],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false
    }
};

static const UMLRTCommsPort * borderports_Simulator_client_0_ptrs[] = 
{
    &borderports_Simulator_client_0[0],
    &borderports_Simulator_client_0[1],
    &borderports_Simulator_client_0[2],
    &borderports_Simulator_client_0[3],
    &borderports_Simulator_client_0[4],
    &borderports_Simulator_client_0[5],
    &borderports_Simulator_client_0[6]
};

static Capsule_Client simulator_client_0( &Client, &Simulator_slots[InstId_Simulator_client_0], borderports_Simulator_client_0_ptrs, NULL, true );

static UMLRTCommsPortFarEnd borderfarEndList_Simulator_client_1[] = 
{
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        1,
        &borderports_Simulator_server1[Capsule_Server::borderport_ServerComm]
    },
    {
        1,
        &borderports_Simulator_server2[Capsule_Server::borderport_ServerComm]
    },
    {
        0,
        NULL
    }
};

UMLRTCommsPort borderports_Simulator_client_1[] = 
{
    {
        &Client,
        Capsule_Client::borderport_ConfigComm,
        &Simulator_slots[InstId_Simulator_client_1],
        1,
        borderfarEndList_Simulator_client_1,
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false
    },
    {
        &Client,
        Capsule_Client::borderport_ConfigTimer,
        &Simulator_slots[InstId_Simulator_client_1],
        1,
        &borderfarEndList_Simulator_client_1[1],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false
    },
    {
        &Client,
        Capsule_Client::borderport_RequestTimer,
        &Simulator_slots[InstId_Simulator_client_1],
        1,
        &borderfarEndList_Simulator_client_1[2],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false
    },
    {
        &Client,
        Capsule_Client::borderport_ResponseTimer,
        &Simulator_slots[InstId_Simulator_client_1],
        1,
        &borderfarEndList_Simulator_client_1[3],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false
    },
    {
        &Client,
        Capsule_Client::borderport_Server1Comm,
        &Simulator_slots[InstId_Simulator_client_1],
        1,
        &borderfarEndList_Simulator_client_1[4],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true
    },
    {
        &Client,
        Capsule_Client::borderport_Server2Comm,
        &Simulator_slots[InstId_Simulator_client_1],
        1,
        &borderfarEndList_Simulator_client_1[5],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true
    },
    {
        &Client,
        Capsule_Client::borderport_Timer,
        &Simulator_slots[InstId_Simulator_client_1],
        1,
        &borderfarEndList_Simulator_client_1[6],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false
    }
};

static const UMLRTCommsPort * borderports_Simulator_client_1_ptrs[] = 
{
    &borderports_Simulator_client_1[0],
    &borderports_Simulator_client_1[1],
    &borderports_Simulator_client_1[2],
    &borderports_Simulator_client_1[3],
    &borderports_Simulator_client_1[4],
    &borderports_Simulator_client_1[5],
    &borderports_Simulator_client_1[6]
};

static Capsule_Client simulator_client_1( &Client, &Simulator_slots[InstId_Simulator_client_1], borderports_Simulator_client_1_ptrs, NULL, true );

static UMLRTCommsPortFarEnd borderfarEndList_Simulator_client_2[] = 
{
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        2,
        &borderports_Simulator_server1[Capsule_Server::borderport_ServerComm]
    },
    {
        2,
        &borderports_Simulator_server2[Capsule_Server::borderport_ServerComm]
    },
    {
        0,
        NULL
    }
};

UMLRTCommsPort borderports_Simulator_client_2[] = 
{
    {
        &Client,
        Capsule_Client::borderport_ConfigComm,
        &Simulator_slots[InstId_Simulator_client_2],
        1,
        borderfarEndList_Simulator_client_2,
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false
    },
    {
        &Client,
        Capsule_Client::borderport_ConfigTimer,
        &Simulator_slots[InstId_Simulator_client_2],
        1,
        &borderfarEndList_Simulator_client_2[1],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false
    },
    {
        &Client,
        Capsule_Client::borderport_RequestTimer,
        &Simulator_slots[InstId_Simulator_client_2],
        1,
        &borderfarEndList_Simulator_client_2[2],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false
    },
    {
        &Client,
        Capsule_Client::borderport_ResponseTimer,
        &Simulator_slots[InstId_Simulator_client_2],
        1,
        &borderfarEndList_Simulator_client_2[3],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false
    },
    {
        &Client,
        Capsule_Client::borderport_Server1Comm,
        &Simulator_slots[InstId_Simulator_client_2],
        1,
        &borderfarEndList_Simulator_client_2[4],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true
    },
    {
        &Client,
        Capsule_Client::borderport_Server2Comm,
        &Simulator_slots[InstId_Simulator_client_2],
        1,
        &borderfarEndList_Simulator_client_2[5],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true
    },
    {
        &Client,
        Capsule_Client::borderport_Timer,
        &Simulator_slots[InstId_Simulator_client_2],
        1,
        &borderfarEndList_Simulator_client_2[6],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false
    }
};

static const UMLRTCommsPort * borderports_Simulator_client_2_ptrs[] = 
{
    &borderports_Simulator_client_2[0],
    &borderports_Simulator_client_2[1],
    &borderports_Simulator_client_2[2],
    &borderports_Simulator_client_2[3],
    &borderports_Simulator_client_2[4],
    &borderports_Simulator_client_2[5],
    &borderports_Simulator_client_2[6]
};

static Capsule_Client simulator_client_2( &Client, &Simulator_slots[InstId_Simulator_client_2], borderports_Simulator_client_2_ptrs, NULL, true );

static UMLRTCommsPortFarEnd borderfarEndList_Simulator_client_3[] = 
{
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        3,
        &borderports_Simulator_server1[Capsule_Server::borderport_ServerComm]
    },
    {
        3,
        &borderports_Simulator_server2[Capsule_Server::borderport_ServerComm]
    },
    {
        0,
        NULL
    }
};

UMLRTCommsPort borderports_Simulator_client_3[] = 
{
    {
        &Client,
        Capsule_Client::borderport_ConfigComm,
        &Simulator_slots[InstId_Simulator_client_3],
        1,
        borderfarEndList_Simulator_client_3,
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false
    },
    {
        &Client,
        Capsule_Client::borderport_ConfigTimer,
        &Simulator_slots[InstId_Simulator_client_3],
        1,
        &borderfarEndList_Simulator_client_3[1],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false
    },
    {
        &Client,
        Capsule_Client::borderport_RequestTimer,
        &Simulator_slots[InstId_Simulator_client_3],
        1,
        &borderfarEndList_Simulator_client_3[2],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false
    },
    {
        &Client,
        Capsule_Client::borderport_ResponseTimer,
        &Simulator_slots[InstId_Simulator_client_3],
        1,
        &borderfarEndList_Simulator_client_3[3],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false
    },
    {
        &Client,
        Capsule_Client::borderport_Server1Comm,
        &Simulator_slots[InstId_Simulator_client_3],
        1,
        &borderfarEndList_Simulator_client_3[4],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true
    },
    {
        &Client,
        Capsule_Client::borderport_Server2Comm,
        &Simulator_slots[InstId_Simulator_client_3],
        1,
        &borderfarEndList_Simulator_client_3[5],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true
    },
    {
        &Client,
        Capsule_Client::borderport_Timer,
        &Simulator_slots[InstId_Simulator_client_3],
        1,
        &borderfarEndList_Simulator_client_3[6],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false
    }
};

static const UMLRTCommsPort * borderports_Simulator_client_3_ptrs[] = 
{
    &borderports_Simulator_client_3[0],
    &borderports_Simulator_client_3[1],
    &borderports_Simulator_client_3[2],
    &borderports_Simulator_client_3[3],
    &borderports_Simulator_client_3[4],
    &borderports_Simulator_client_3[5],
    &borderports_Simulator_client_3[6]
};

static Capsule_Client simulator_client_3( &Client, &Simulator_slots[InstId_Simulator_client_3], borderports_Simulator_client_3_ptrs, NULL, true );

static UMLRTCommsPortFarEnd borderfarEndList_Simulator_client_4[] = 
{
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        4,
        &borderports_Simulator_server1[Capsule_Server::borderport_ServerComm]
    },
    {
        4,
        &borderports_Simulator_server2[Capsule_Server::borderport_ServerComm]
    },
    {
        0,
        NULL
    }
};

UMLRTCommsPort borderports_Simulator_client_4[] = 
{
    {
        &Client,
        Capsule_Client::borderport_ConfigComm,
        &Simulator_slots[InstId_Simulator_client_4],
        1,
        borderfarEndList_Simulator_client_4,
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false
    },
    {
        &Client,
        Capsule_Client::borderport_ConfigTimer,
        &Simulator_slots[InstId_Simulator_client_4],
        1,
        &borderfarEndList_Simulator_client_4[1],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false
    },
    {
        &Client,
        Capsule_Client::borderport_RequestTimer,
        &Simulator_slots[InstId_Simulator_client_4],
        1,
        &borderfarEndList_Simulator_client_4[2],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false
    },
    {
        &Client,
        Capsule_Client::borderport_ResponseTimer,
        &Simulator_slots[InstId_Simulator_client_4],
        1,
        &borderfarEndList_Simulator_client_4[3],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false
    },
    {
        &Client,
        Capsule_Client::borderport_Server1Comm,
        &Simulator_slots[InstId_Simulator_client_4],
        1,
        &borderfarEndList_Simulator_client_4[4],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true
    },
    {
        &Client,
        Capsule_Client::borderport_Server2Comm,
        &Simulator_slots[InstId_Simulator_client_4],
        1,
        &borderfarEndList_Simulator_client_4[5],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true
    },
    {
        &Client,
        Capsule_Client::borderport_Timer,
        &Simulator_slots[InstId_Simulator_client_4],
        1,
        &borderfarEndList_Simulator_client_4[6],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false
    }
};

static const UMLRTCommsPort * borderports_Simulator_client_4_ptrs[] = 
{
    &borderports_Simulator_client_4[0],
    &borderports_Simulator_client_4[1],
    &borderports_Simulator_client_4[2],
    &borderports_Simulator_client_4[3],
    &borderports_Simulator_client_4[4],
    &borderports_Simulator_client_4[5],
    &borderports_Simulator_client_4[6]
};

static Capsule_Client simulator_client_4( &Client, &Simulator_slots[InstId_Simulator_client_4], borderports_Simulator_client_4_ptrs, NULL, true );

static UMLRTCommsPortFarEnd borderfarEndList_Simulator_server1[] = 
{
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        &borderports_Simulator_server2[Capsule_Server::borderport_Slave]
    },
    {
        0,
        NULL
    },
    {
        0,
        &borderports_Simulator_client_0[Capsule_Client::borderport_Server1Comm]
    },
    {
        0,
        &borderports_Simulator_client_1[Capsule_Client::borderport_Server1Comm]
    },
    {
        0,
        &borderports_Simulator_client_2[Capsule_Client::borderport_Server1Comm]
    },
    {
        0,
        &borderports_Simulator_client_3[Capsule_Client::borderport_Server1Comm]
    },
    {
        0,
        &borderports_Simulator_client_4[Capsule_Client::borderport_Server1Comm]
    },
    {
        0,
        &borderports_Simulator_server2[Capsule_Server::borderport_Master]
    },
    {
        0,
        NULL
    }
};

UMLRTCommsPort borderports_Simulator_server1[] = 
{
    {
        &Server,
        Capsule_Server::borderport_ConfigComm,
        &Simulator_slots[InstId_Simulator_server1],
        1,
        borderfarEndList_Simulator_server1,
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false
    },
    {
        &Server,
        Capsule_Server::borderport_KeepAliveTimer,
        &Simulator_slots[InstId_Simulator_server1],
        1,
        &borderfarEndList_Simulator_server1[1],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false
    },
    {
        &Server,
        Capsule_Server::borderport_Master,
        &Simulator_slots[InstId_Simulator_server1],
        1,
        &borderfarEndList_Simulator_server1[2],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true
    },
    {
        &Server,
        Capsule_Server::borderport_MasterAnnounceTimer,
        &Simulator_slots[InstId_Simulator_server1],
        1,
        &borderfarEndList_Simulator_server1[3],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false
    },
    {
        &Server,
        Capsule_Server::borderport_ServerComm,
        &Simulator_slots[InstId_Simulator_server1],
        5,
        &borderfarEndList_Simulator_server1[4],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true
    },
    {
        &Server,
        Capsule_Server::borderport_Slave,
        &Simulator_slots[InstId_Simulator_server1],
        1,
        &borderfarEndList_Simulator_server1[9],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true
    },
    {
        &Server,
        Capsule_Server::borderport_Timer,
        &Simulator_slots[InstId_Simulator_server1],
        1,
        &borderfarEndList_Simulator_server1[10],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false
    }
};

static const UMLRTCommsPort * borderports_Simulator_server1_ptrs[] = 
{
    &borderports_Simulator_server1[0],
    &borderports_Simulator_server1[1],
    &borderports_Simulator_server1[2],
    &borderports_Simulator_server1[3],
    &borderports_Simulator_server1[4],
    &borderports_Simulator_server1[5],
    &borderports_Simulator_server1[6]
};

static Capsule_Server simulator_server1( &Server, &Simulator_slots[InstId_Simulator_server1], borderports_Simulator_server1_ptrs, NULL, true );

static UMLRTCommsPortFarEnd borderfarEndList_Simulator_server2[] = 
{
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        &borderports_Simulator_server1[Capsule_Server::borderport_Slave]
    },
    {
        0,
        NULL
    },
    {
        0,
        &borderports_Simulator_client_0[Capsule_Client::borderport_Server2Comm]
    },
    {
        0,
        &borderports_Simulator_client_1[Capsule_Client::borderport_Server2Comm]
    },
    {
        0,
        &borderports_Simulator_client_2[Capsule_Client::borderport_Server2Comm]
    },
    {
        0,
        &borderports_Simulator_client_3[Capsule_Client::borderport_Server2Comm]
    },
    {
        0,
        &borderports_Simulator_client_4[Capsule_Client::borderport_Server2Comm]
    },
    {
        0,
        &borderports_Simulator_server1[Capsule_Server::borderport_Master]
    },
    {
        0,
        NULL
    }
};

UMLRTCommsPort borderports_Simulator_server2[] = 
{
    {
        &Server,
        Capsule_Server::borderport_ConfigComm,
        &Simulator_slots[InstId_Simulator_server2],
        1,
        borderfarEndList_Simulator_server2,
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false
    },
    {
        &Server,
        Capsule_Server::borderport_KeepAliveTimer,
        &Simulator_slots[InstId_Simulator_server2],
        1,
        &borderfarEndList_Simulator_server2[1],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false
    },
    {
        &Server,
        Capsule_Server::borderport_Master,
        &Simulator_slots[InstId_Simulator_server2],
        1,
        &borderfarEndList_Simulator_server2[2],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true
    },
    {
        &Server,
        Capsule_Server::borderport_MasterAnnounceTimer,
        &Simulator_slots[InstId_Simulator_server2],
        1,
        &borderfarEndList_Simulator_server2[3],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false
    },
    {
        &Server,
        Capsule_Server::borderport_ServerComm,
        &Simulator_slots[InstId_Simulator_server2],
        5,
        &borderfarEndList_Simulator_server2[4],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true
    },
    {
        &Server,
        Capsule_Server::borderport_Slave,
        &Simulator_slots[InstId_Simulator_server2],
        1,
        &borderfarEndList_Simulator_server2[9],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true
    },
    {
        &Server,
        Capsule_Server::borderport_Timer,
        &Simulator_slots[InstId_Simulator_server2],
        1,
        &borderfarEndList_Simulator_server2[10],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false
    }
};

static const UMLRTCommsPort * borderports_Simulator_server2_ptrs[] = 
{
    &borderports_Simulator_server2[0],
    &borderports_Simulator_server2[1],
    &borderports_Simulator_server2[2],
    &borderports_Simulator_server2[3],
    &borderports_Simulator_server2[4],
    &borderports_Simulator_server2[5],
    &borderports_Simulator_server2[6]
};

static Capsule_Server simulator_server2( &Server, &Simulator_slots[InstId_Simulator_server2], borderports_Simulator_server2_ptrs, NULL, true );

UMLRTSlot Simulator_slots[] = 
{
    {
        "Simulator",
        0,
        &Simulator,
        NULL,
        0,
        &simulator,
        &DefaultController_,
        4,
        parts_Simulator,
        0,
        NULL,
        NULL,
        true,
        false
    },
    {
        "Simulator.ENV",
        0,
        &ENV,
        &Simulator,
        Capsule_Simulator::part_ENV,
        &simulator_ENV,
        &DefaultController_,
        0,
        NULL,
        7,
        borderports_Simulator_ENV,
        NULL,
        true,
        false
    },
    {
        "Simulator.client[0]",
        0,
        &Client,
        &Simulator,
        Capsule_Simulator::part_client,
        &simulator_client_0,
        &DefaultController_,
        0,
        NULL,
        7,
        borderports_Simulator_client_0,
        NULL,
        true,
        false
    },
    {
        "Simulator.client[1]",
        1,
        &Client,
        &Simulator,
        Capsule_Simulator::part_client,
        &simulator_client_1,
        &DefaultController_,
        0,
        NULL,
        7,
        borderports_Simulator_client_1,
        NULL,
        true,
        false
    },
    {
        "Simulator.client[2]",
        2,
        &Client,
        &Simulator,
        Capsule_Simulator::part_client,
        &simulator_client_2,
        &DefaultController_,
        0,
        NULL,
        7,
        borderports_Simulator_client_2,
        NULL,
        true,
        false
    },
    {
        "Simulator.client[3]",
        3,
        &Client,
        &Simulator,
        Capsule_Simulator::part_client,
        &simulator_client_3,
        &DefaultController_,
        0,
        NULL,
        7,
        borderports_Simulator_client_3,
        NULL,
        true,
        false
    },
    {
        "Simulator.client[4]",
        4,
        &Client,
        &Simulator,
        Capsule_Simulator::part_client,
        &simulator_client_4,
        &DefaultController_,
        0,
        NULL,
        7,
        borderports_Simulator_client_4,
        NULL,
        true,
        false
    },
    {
        "Simulator.server1",
        0,
        &Server,
        &Simulator,
        Capsule_Simulator::part_server1,
        &simulator_server1,
        &DefaultController_,
        0,
        NULL,
        7,
        borderports_Simulator_server1,
        NULL,
        true,
        false
    },
    {
        "Simulator.server2",
        0,
        &Server,
        &Simulator,
        Capsule_Simulator::part_server2,
        &simulator_server2,
        &DefaultController_,
        0,
        NULL,
        7,
        borderports_Simulator_server2,
        NULL,
        true,
        false
    }
};

