
#include "Debug__TopControllers.hh"

#include "Client.hh"
#include "Debug__Top.hh"
#include "ENV.hh"
#include "GateWay.hh"
#include "Server.hh"
#include "Simulator.hh"
#include "umlrtcapsuleclass.hh"
#include "umlrtcapsulepart.hh"
#include "umlrtcommsport.hh"
#include "umlrtcommsportfarend.hh"
#include "umlrtcontroller.hh"
#include "umlrtslot.hh"
#include <cstddef>


static UMLRTController DefaultController_( "DefaultController" );

UMLRTController * DefaultController = &DefaultController_;

static Capsule_Debug__Top debug__Top( &Debug__Top, &Debug__Top_slots[InstId_Debug__Top], NULL, NULL, true );

static UMLRTSlot * slots_Debug__Top[] = 
{
    &Debug__Top_slots[InstId_Debug__Top_Debug__Gateway],
    &Debug__Top_slots[InstId_Debug__Top_Debug__Simulator]
};

static UMLRTCapsulePart parts_Debug__Top[] = 
{
    {
        &Debug__Top,
        Capsule_Debug__Top::part_Debug__Gateway,
        1,
        &slots_Debug__Top[0]
    },
    {
        &Debug__Top,
        Capsule_Debug__Top::part_Debug__Simulator,
        1,
        &slots_Debug__Top[1]
    }
};

static UMLRTCommsPortFarEnd borderfarEndList_Debug__Top_Debug__Gateway[] = 
{
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    }
};

UMLRTCommsPort borderports_Debug__Top_Debug__Gateway[] = 
{
    {
        &GateWay,
        Capsule_GateWay::borderport_commandTimer,
        &Debug__Top_slots[InstId_Debug__Top_Debug__Gateway],
        1,
        borderfarEndList_Debug__Top_Debug__Gateway,
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true
    },
    {
        &GateWay,
        Capsule_GateWay::borderport_configTimer,
        &Debug__Top_slots[InstId_Debug__Top_Debug__Gateway],
        1,
        &borderfarEndList_Debug__Top_Debug__Gateway[1],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true
    },
    {
        &GateWay,
        Capsule_GateWay::borderport_extComm,
        &Debug__Top_slots[InstId_Debug__Top_Debug__Gateway],
        50,
        &borderfarEndList_Debug__Top_Debug__Gateway[2],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false
    }
};

static const UMLRTCommsPort * borderports_Debug__Top_Debug__Gateway_ptrs[] = 
{
    &borderports_Debug__Top_Debug__Gateway[0],
    &borderports_Debug__Top_Debug__Gateway[1],
    &borderports_Debug__Top_Debug__Gateway[2]
};

static Capsule_GateWay debug__Top_Debug__Gateway( &GateWay, &Debug__Top_slots[InstId_Debug__Top_Debug__Gateway], borderports_Debug__Top_Debug__Gateway_ptrs, NULL, true );

static Capsule_Simulator debug__Top_Debug__Simulator( &Simulator, &Debug__Top_slots[InstId_Debug__Top_Debug__Simulator], NULL, NULL, true );

static UMLRTSlot * slots_Debug__Top_Debug__Simulator[] = 
{
    &Debug__Top_slots[InstId_Debug__Top_Debug__Simulator_ENV],
    &Debug__Top_slots[InstId_Debug__Top_Debug__Simulator_client_0],
    &Debug__Top_slots[InstId_Debug__Top_Debug__Simulator_client_1],
    &Debug__Top_slots[InstId_Debug__Top_Debug__Simulator_client_2],
    &Debug__Top_slots[InstId_Debug__Top_Debug__Simulator_client_3],
    &Debug__Top_slots[InstId_Debug__Top_Debug__Simulator_client_4],
    &Debug__Top_slots[InstId_Debug__Top_Debug__Simulator_server1],
    &Debug__Top_slots[InstId_Debug__Top_Debug__Simulator_server2]
};

static UMLRTCapsulePart parts_Debug__Top_Debug__Simulator[] = 
{
    {
        &Simulator,
        Capsule_Simulator::part_ENV,
        1,
        &slots_Debug__Top_Debug__Simulator[0]
    },
    {
        &Simulator,
        Capsule_Simulator::part_client,
        5,
        &slots_Debug__Top_Debug__Simulator[1]
    },
    {
        &Simulator,
        Capsule_Simulator::part_server1,
        1,
        &slots_Debug__Top_Debug__Simulator[6]
    },
    {
        &Simulator,
        Capsule_Simulator::part_server2,
        1,
        &slots_Debug__Top_Debug__Simulator[7]
    }
};

static UMLRTCommsPortFarEnd borderfarEndList_Debug__Top_Debug__Simulator_ENV[] = 
{
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    }
};

UMLRTCommsPort borderports_Debug__Top_Debug__Simulator_ENV[] = 
{
    {
        &ENV,
        Capsule_ENV::borderport_AnnouncmentServer1,
        &Debug__Top_slots[InstId_Debug__Top_Debug__Simulator_ENV],
        1,
        borderfarEndList_Debug__Top_Debug__Simulator_ENV,
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false
    },
    {
        &ENV,
        Capsule_ENV::borderport_AnnouncmentServer2,
        &Debug__Top_slots[InstId_Debug__Top_Debug__Simulator_ENV],
        1,
        &borderfarEndList_Debug__Top_Debug__Simulator_ENV[1],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false
    },
    {
        &ENV,
        Capsule_ENV::borderport_BITTimer,
        &Debug__Top_slots[InstId_Debug__Top_Debug__Simulator_ENV],
        1,
        &borderfarEndList_Debug__Top_Debug__Simulator_ENV[2],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false
    },
    {
        &ENV,
        Capsule_ENV::borderport_ConfigComm,
        &Debug__Top_slots[InstId_Debug__Top_Debug__Simulator_ENV],
        7,
        &borderfarEndList_Debug__Top_Debug__Simulator_ENV[3],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        true,
        false,
        false
    },
    {
        &ENV,
        Capsule_ENV::borderport_FailureTimer,
        &Debug__Top_slots[InstId_Debug__Top_Debug__Simulator_ENV],
        1,
        &borderfarEndList_Debug__Top_Debug__Simulator_ENV[10],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false
    },
    {
        &ENV,
        Capsule_ENV::borderport_GeneralTimer,
        &Debug__Top_slots[InstId_Debug__Top_Debug__Simulator_ENV],
        1,
        &borderfarEndList_Debug__Top_Debug__Simulator_ENV[11],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false
    },
    {
        &ENV,
        Capsule_ENV::borderport_configTimer,
        &Debug__Top_slots[InstId_Debug__Top_Debug__Simulator_ENV],
        1,
        &borderfarEndList_Debug__Top_Debug__Simulator_ENV[12],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false
    },
    {
        &ENV,
        Capsule_ENV::borderport_extComm,
        &Debug__Top_slots[InstId_Debug__Top_Debug__Simulator_ENV],
        1,
        &borderfarEndList_Debug__Top_Debug__Simulator_ENV[13],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        true,
        false,
        false,
        true,
        false,
        false,
        false
    }
};

static const UMLRTCommsPort * borderports_Debug__Top_Debug__Simulator_ENV_ptrs[] = 
{
    &borderports_Debug__Top_Debug__Simulator_ENV[0],
    &borderports_Debug__Top_Debug__Simulator_ENV[1],
    &borderports_Debug__Top_Debug__Simulator_ENV[2],
    &borderports_Debug__Top_Debug__Simulator_ENV[3],
    &borderports_Debug__Top_Debug__Simulator_ENV[4],
    &borderports_Debug__Top_Debug__Simulator_ENV[5],
    &borderports_Debug__Top_Debug__Simulator_ENV[6],
    &borderports_Debug__Top_Debug__Simulator_ENV[7]
};

static Capsule_ENV debug__Top_Debug__Simulator_ENV( &ENV, &Debug__Top_slots[InstId_Debug__Top_Debug__Simulator_ENV], borderports_Debug__Top_Debug__Simulator_ENV_ptrs, NULL, true );

static UMLRTCommsPortFarEnd borderfarEndList_Debug__Top_Debug__Simulator_client_0[] = 
{
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        &borderports_Debug__Top_Debug__Simulator_server1[Capsule_Server::borderport_ServerComm]
    },
    {
        0,
        &borderports_Debug__Top_Debug__Simulator_server2[Capsule_Server::borderport_ServerComm]
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    }
};

UMLRTCommsPort borderports_Debug__Top_Debug__Simulator_client_0[] = 
{
    {
        &Client,
        Capsule_Client::borderport_ConfigComm,
        &Debug__Top_slots[InstId_Debug__Top_Debug__Simulator_client_0],
        1,
        borderfarEndList_Debug__Top_Debug__Simulator_client_0,
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false
    },
    {
        &Client,
        Capsule_Client::borderport_ConfigTimer,
        &Debug__Top_slots[InstId_Debug__Top_Debug__Simulator_client_0],
        1,
        &borderfarEndList_Debug__Top_Debug__Simulator_client_0[1],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false
    },
    {
        &Client,
        Capsule_Client::borderport_RequestTimer,
        &Debug__Top_slots[InstId_Debug__Top_Debug__Simulator_client_0],
        1,
        &borderfarEndList_Debug__Top_Debug__Simulator_client_0[2],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false
    },
    {
        &Client,
        Capsule_Client::borderport_ResponseTimer,
        &Debug__Top_slots[InstId_Debug__Top_Debug__Simulator_client_0],
        1,
        &borderfarEndList_Debug__Top_Debug__Simulator_client_0[3],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false
    },
    {
        &Client,
        Capsule_Client::borderport_Server1Comm,
        &Debug__Top_slots[InstId_Debug__Top_Debug__Simulator_client_0],
        1,
        &borderfarEndList_Debug__Top_Debug__Simulator_client_0[4],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true
    },
    {
        &Client,
        Capsule_Client::borderport_Server2Comm,
        &Debug__Top_slots[InstId_Debug__Top_Debug__Simulator_client_0],
        1,
        &borderfarEndList_Debug__Top_Debug__Simulator_client_0[5],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true
    },
    {
        &Client,
        Capsule_Client::borderport_Timer,
        &Debug__Top_slots[InstId_Debug__Top_Debug__Simulator_client_0],
        1,
        &borderfarEndList_Debug__Top_Debug__Simulator_client_0[6],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false
    },
    {
        &Client,
        Capsule_Client::borderport_extComm,
        &Debug__Top_slots[InstId_Debug__Top_Debug__Simulator_client_0],
        1,
        &borderfarEndList_Debug__Top_Debug__Simulator_client_0[7],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        true,
        false,
        false,
        true,
        false,
        false,
        false
    }
};

static const UMLRTCommsPort * borderports_Debug__Top_Debug__Simulator_client_0_ptrs[] = 
{
    &borderports_Debug__Top_Debug__Simulator_client_0[0],
    &borderports_Debug__Top_Debug__Simulator_client_0[1],
    &borderports_Debug__Top_Debug__Simulator_client_0[2],
    &borderports_Debug__Top_Debug__Simulator_client_0[3],
    &borderports_Debug__Top_Debug__Simulator_client_0[4],
    &borderports_Debug__Top_Debug__Simulator_client_0[5],
    &borderports_Debug__Top_Debug__Simulator_client_0[6],
    &borderports_Debug__Top_Debug__Simulator_client_0[7]
};

static Capsule_Client debug__Top_Debug__Simulator_client_0( &Client, &Debug__Top_slots[InstId_Debug__Top_Debug__Simulator_client_0], borderports_Debug__Top_Debug__Simulator_client_0_ptrs, NULL, true );

static UMLRTCommsPortFarEnd borderfarEndList_Debug__Top_Debug__Simulator_client_1[] = 
{
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        1,
        &borderports_Debug__Top_Debug__Simulator_server1[Capsule_Server::borderport_ServerComm]
    },
    {
        1,
        &borderports_Debug__Top_Debug__Simulator_server2[Capsule_Server::borderport_ServerComm]
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    }
};

UMLRTCommsPort borderports_Debug__Top_Debug__Simulator_client_1[] = 
{
    {
        &Client,
        Capsule_Client::borderport_ConfigComm,
        &Debug__Top_slots[InstId_Debug__Top_Debug__Simulator_client_1],
        1,
        borderfarEndList_Debug__Top_Debug__Simulator_client_1,
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false
    },
    {
        &Client,
        Capsule_Client::borderport_ConfigTimer,
        &Debug__Top_slots[InstId_Debug__Top_Debug__Simulator_client_1],
        1,
        &borderfarEndList_Debug__Top_Debug__Simulator_client_1[1],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false
    },
    {
        &Client,
        Capsule_Client::borderport_RequestTimer,
        &Debug__Top_slots[InstId_Debug__Top_Debug__Simulator_client_1],
        1,
        &borderfarEndList_Debug__Top_Debug__Simulator_client_1[2],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false
    },
    {
        &Client,
        Capsule_Client::borderport_ResponseTimer,
        &Debug__Top_slots[InstId_Debug__Top_Debug__Simulator_client_1],
        1,
        &borderfarEndList_Debug__Top_Debug__Simulator_client_1[3],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false
    },
    {
        &Client,
        Capsule_Client::borderport_Server1Comm,
        &Debug__Top_slots[InstId_Debug__Top_Debug__Simulator_client_1],
        1,
        &borderfarEndList_Debug__Top_Debug__Simulator_client_1[4],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true
    },
    {
        &Client,
        Capsule_Client::borderport_Server2Comm,
        &Debug__Top_slots[InstId_Debug__Top_Debug__Simulator_client_1],
        1,
        &borderfarEndList_Debug__Top_Debug__Simulator_client_1[5],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true
    },
    {
        &Client,
        Capsule_Client::borderport_Timer,
        &Debug__Top_slots[InstId_Debug__Top_Debug__Simulator_client_1],
        1,
        &borderfarEndList_Debug__Top_Debug__Simulator_client_1[6],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false
    },
    {
        &Client,
        Capsule_Client::borderport_extComm,
        &Debug__Top_slots[InstId_Debug__Top_Debug__Simulator_client_1],
        1,
        &borderfarEndList_Debug__Top_Debug__Simulator_client_1[7],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        true,
        false,
        false,
        true,
        false,
        false,
        false
    }
};

static const UMLRTCommsPort * borderports_Debug__Top_Debug__Simulator_client_1_ptrs[] = 
{
    &borderports_Debug__Top_Debug__Simulator_client_1[0],
    &borderports_Debug__Top_Debug__Simulator_client_1[1],
    &borderports_Debug__Top_Debug__Simulator_client_1[2],
    &borderports_Debug__Top_Debug__Simulator_client_1[3],
    &borderports_Debug__Top_Debug__Simulator_client_1[4],
    &borderports_Debug__Top_Debug__Simulator_client_1[5],
    &borderports_Debug__Top_Debug__Simulator_client_1[6],
    &borderports_Debug__Top_Debug__Simulator_client_1[7]
};

static Capsule_Client debug__Top_Debug__Simulator_client_1( &Client, &Debug__Top_slots[InstId_Debug__Top_Debug__Simulator_client_1], borderports_Debug__Top_Debug__Simulator_client_1_ptrs, NULL, true );

static UMLRTCommsPortFarEnd borderfarEndList_Debug__Top_Debug__Simulator_client_2[] = 
{
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        2,
        &borderports_Debug__Top_Debug__Simulator_server1[Capsule_Server::borderport_ServerComm]
    },
    {
        2,
        &borderports_Debug__Top_Debug__Simulator_server2[Capsule_Server::borderport_ServerComm]
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    }
};

UMLRTCommsPort borderports_Debug__Top_Debug__Simulator_client_2[] = 
{
    {
        &Client,
        Capsule_Client::borderport_ConfigComm,
        &Debug__Top_slots[InstId_Debug__Top_Debug__Simulator_client_2],
        1,
        borderfarEndList_Debug__Top_Debug__Simulator_client_2,
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false
    },
    {
        &Client,
        Capsule_Client::borderport_ConfigTimer,
        &Debug__Top_slots[InstId_Debug__Top_Debug__Simulator_client_2],
        1,
        &borderfarEndList_Debug__Top_Debug__Simulator_client_2[1],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false
    },
    {
        &Client,
        Capsule_Client::borderport_RequestTimer,
        &Debug__Top_slots[InstId_Debug__Top_Debug__Simulator_client_2],
        1,
        &borderfarEndList_Debug__Top_Debug__Simulator_client_2[2],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false
    },
    {
        &Client,
        Capsule_Client::borderport_ResponseTimer,
        &Debug__Top_slots[InstId_Debug__Top_Debug__Simulator_client_2],
        1,
        &borderfarEndList_Debug__Top_Debug__Simulator_client_2[3],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false
    },
    {
        &Client,
        Capsule_Client::borderport_Server1Comm,
        &Debug__Top_slots[InstId_Debug__Top_Debug__Simulator_client_2],
        1,
        &borderfarEndList_Debug__Top_Debug__Simulator_client_2[4],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true
    },
    {
        &Client,
        Capsule_Client::borderport_Server2Comm,
        &Debug__Top_slots[InstId_Debug__Top_Debug__Simulator_client_2],
        1,
        &borderfarEndList_Debug__Top_Debug__Simulator_client_2[5],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true
    },
    {
        &Client,
        Capsule_Client::borderport_Timer,
        &Debug__Top_slots[InstId_Debug__Top_Debug__Simulator_client_2],
        1,
        &borderfarEndList_Debug__Top_Debug__Simulator_client_2[6],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false
    },
    {
        &Client,
        Capsule_Client::borderport_extComm,
        &Debug__Top_slots[InstId_Debug__Top_Debug__Simulator_client_2],
        1,
        &borderfarEndList_Debug__Top_Debug__Simulator_client_2[7],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        true,
        false,
        false,
        true,
        false,
        false,
        false
    }
};

static const UMLRTCommsPort * borderports_Debug__Top_Debug__Simulator_client_2_ptrs[] = 
{
    &borderports_Debug__Top_Debug__Simulator_client_2[0],
    &borderports_Debug__Top_Debug__Simulator_client_2[1],
    &borderports_Debug__Top_Debug__Simulator_client_2[2],
    &borderports_Debug__Top_Debug__Simulator_client_2[3],
    &borderports_Debug__Top_Debug__Simulator_client_2[4],
    &borderports_Debug__Top_Debug__Simulator_client_2[5],
    &borderports_Debug__Top_Debug__Simulator_client_2[6],
    &borderports_Debug__Top_Debug__Simulator_client_2[7]
};

static Capsule_Client debug__Top_Debug__Simulator_client_2( &Client, &Debug__Top_slots[InstId_Debug__Top_Debug__Simulator_client_2], borderports_Debug__Top_Debug__Simulator_client_2_ptrs, NULL, true );

static UMLRTCommsPortFarEnd borderfarEndList_Debug__Top_Debug__Simulator_client_3[] = 
{
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        3,
        &borderports_Debug__Top_Debug__Simulator_server1[Capsule_Server::borderport_ServerComm]
    },
    {
        3,
        &borderports_Debug__Top_Debug__Simulator_server2[Capsule_Server::borderport_ServerComm]
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    }
};

UMLRTCommsPort borderports_Debug__Top_Debug__Simulator_client_3[] = 
{
    {
        &Client,
        Capsule_Client::borderport_ConfigComm,
        &Debug__Top_slots[InstId_Debug__Top_Debug__Simulator_client_3],
        1,
        borderfarEndList_Debug__Top_Debug__Simulator_client_3,
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false
    },
    {
        &Client,
        Capsule_Client::borderport_ConfigTimer,
        &Debug__Top_slots[InstId_Debug__Top_Debug__Simulator_client_3],
        1,
        &borderfarEndList_Debug__Top_Debug__Simulator_client_3[1],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false
    },
    {
        &Client,
        Capsule_Client::borderport_RequestTimer,
        &Debug__Top_slots[InstId_Debug__Top_Debug__Simulator_client_3],
        1,
        &borderfarEndList_Debug__Top_Debug__Simulator_client_3[2],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false
    },
    {
        &Client,
        Capsule_Client::borderport_ResponseTimer,
        &Debug__Top_slots[InstId_Debug__Top_Debug__Simulator_client_3],
        1,
        &borderfarEndList_Debug__Top_Debug__Simulator_client_3[3],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false
    },
    {
        &Client,
        Capsule_Client::borderport_Server1Comm,
        &Debug__Top_slots[InstId_Debug__Top_Debug__Simulator_client_3],
        1,
        &borderfarEndList_Debug__Top_Debug__Simulator_client_3[4],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true
    },
    {
        &Client,
        Capsule_Client::borderport_Server2Comm,
        &Debug__Top_slots[InstId_Debug__Top_Debug__Simulator_client_3],
        1,
        &borderfarEndList_Debug__Top_Debug__Simulator_client_3[5],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true
    },
    {
        &Client,
        Capsule_Client::borderport_Timer,
        &Debug__Top_slots[InstId_Debug__Top_Debug__Simulator_client_3],
        1,
        &borderfarEndList_Debug__Top_Debug__Simulator_client_3[6],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false
    },
    {
        &Client,
        Capsule_Client::borderport_extComm,
        &Debug__Top_slots[InstId_Debug__Top_Debug__Simulator_client_3],
        1,
        &borderfarEndList_Debug__Top_Debug__Simulator_client_3[7],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        true,
        false,
        false,
        true,
        false,
        false,
        false
    }
};

static const UMLRTCommsPort * borderports_Debug__Top_Debug__Simulator_client_3_ptrs[] = 
{
    &borderports_Debug__Top_Debug__Simulator_client_3[0],
    &borderports_Debug__Top_Debug__Simulator_client_3[1],
    &borderports_Debug__Top_Debug__Simulator_client_3[2],
    &borderports_Debug__Top_Debug__Simulator_client_3[3],
    &borderports_Debug__Top_Debug__Simulator_client_3[4],
    &borderports_Debug__Top_Debug__Simulator_client_3[5],
    &borderports_Debug__Top_Debug__Simulator_client_3[6],
    &borderports_Debug__Top_Debug__Simulator_client_3[7]
};

static Capsule_Client debug__Top_Debug__Simulator_client_3( &Client, &Debug__Top_slots[InstId_Debug__Top_Debug__Simulator_client_3], borderports_Debug__Top_Debug__Simulator_client_3_ptrs, NULL, true );

static UMLRTCommsPortFarEnd borderfarEndList_Debug__Top_Debug__Simulator_client_4[] = 
{
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        4,
        &borderports_Debug__Top_Debug__Simulator_server1[Capsule_Server::borderport_ServerComm]
    },
    {
        4,
        &borderports_Debug__Top_Debug__Simulator_server2[Capsule_Server::borderport_ServerComm]
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    }
};

UMLRTCommsPort borderports_Debug__Top_Debug__Simulator_client_4[] = 
{
    {
        &Client,
        Capsule_Client::borderport_ConfigComm,
        &Debug__Top_slots[InstId_Debug__Top_Debug__Simulator_client_4],
        1,
        borderfarEndList_Debug__Top_Debug__Simulator_client_4,
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false
    },
    {
        &Client,
        Capsule_Client::borderport_ConfigTimer,
        &Debug__Top_slots[InstId_Debug__Top_Debug__Simulator_client_4],
        1,
        &borderfarEndList_Debug__Top_Debug__Simulator_client_4[1],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false
    },
    {
        &Client,
        Capsule_Client::borderport_RequestTimer,
        &Debug__Top_slots[InstId_Debug__Top_Debug__Simulator_client_4],
        1,
        &borderfarEndList_Debug__Top_Debug__Simulator_client_4[2],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false
    },
    {
        &Client,
        Capsule_Client::borderport_ResponseTimer,
        &Debug__Top_slots[InstId_Debug__Top_Debug__Simulator_client_4],
        1,
        &borderfarEndList_Debug__Top_Debug__Simulator_client_4[3],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false
    },
    {
        &Client,
        Capsule_Client::borderport_Server1Comm,
        &Debug__Top_slots[InstId_Debug__Top_Debug__Simulator_client_4],
        1,
        &borderfarEndList_Debug__Top_Debug__Simulator_client_4[4],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true
    },
    {
        &Client,
        Capsule_Client::borderport_Server2Comm,
        &Debug__Top_slots[InstId_Debug__Top_Debug__Simulator_client_4],
        1,
        &borderfarEndList_Debug__Top_Debug__Simulator_client_4[5],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true
    },
    {
        &Client,
        Capsule_Client::borderport_Timer,
        &Debug__Top_slots[InstId_Debug__Top_Debug__Simulator_client_4],
        1,
        &borderfarEndList_Debug__Top_Debug__Simulator_client_4[6],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false
    },
    {
        &Client,
        Capsule_Client::borderport_extComm,
        &Debug__Top_slots[InstId_Debug__Top_Debug__Simulator_client_4],
        1,
        &borderfarEndList_Debug__Top_Debug__Simulator_client_4[7],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        true,
        false,
        false,
        true,
        false,
        false,
        false
    }
};

static const UMLRTCommsPort * borderports_Debug__Top_Debug__Simulator_client_4_ptrs[] = 
{
    &borderports_Debug__Top_Debug__Simulator_client_4[0],
    &borderports_Debug__Top_Debug__Simulator_client_4[1],
    &borderports_Debug__Top_Debug__Simulator_client_4[2],
    &borderports_Debug__Top_Debug__Simulator_client_4[3],
    &borderports_Debug__Top_Debug__Simulator_client_4[4],
    &borderports_Debug__Top_Debug__Simulator_client_4[5],
    &borderports_Debug__Top_Debug__Simulator_client_4[6],
    &borderports_Debug__Top_Debug__Simulator_client_4[7]
};

static Capsule_Client debug__Top_Debug__Simulator_client_4( &Client, &Debug__Top_slots[InstId_Debug__Top_Debug__Simulator_client_4], borderports_Debug__Top_Debug__Simulator_client_4_ptrs, NULL, true );

static UMLRTCommsPortFarEnd borderfarEndList_Debug__Top_Debug__Simulator_server1[] = 
{
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        &borderports_Debug__Top_Debug__Simulator_server2[Capsule_Server::borderport_Slave]
    },
    {
        0,
        NULL
    },
    {
        0,
        &borderports_Debug__Top_Debug__Simulator_client_0[Capsule_Client::borderport_Server1Comm]
    },
    {
        0,
        &borderports_Debug__Top_Debug__Simulator_client_1[Capsule_Client::borderport_Server1Comm]
    },
    {
        0,
        &borderports_Debug__Top_Debug__Simulator_client_2[Capsule_Client::borderport_Server1Comm]
    },
    {
        0,
        &borderports_Debug__Top_Debug__Simulator_client_3[Capsule_Client::borderport_Server1Comm]
    },
    {
        0,
        &borderports_Debug__Top_Debug__Simulator_client_4[Capsule_Client::borderport_Server1Comm]
    },
    {
        0,
        &borderports_Debug__Top_Debug__Simulator_server2[Capsule_Server::borderport_Master]
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    }
};

UMLRTCommsPort borderports_Debug__Top_Debug__Simulator_server1[] = 
{
    {
        &Server,
        Capsule_Server::borderport_ConfigComm,
        &Debug__Top_slots[InstId_Debug__Top_Debug__Simulator_server1],
        1,
        borderfarEndList_Debug__Top_Debug__Simulator_server1,
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false
    },
    {
        &Server,
        Capsule_Server::borderport_KeepAliveTimer,
        &Debug__Top_slots[InstId_Debug__Top_Debug__Simulator_server1],
        1,
        &borderfarEndList_Debug__Top_Debug__Simulator_server1[1],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false
    },
    {
        &Server,
        Capsule_Server::borderport_Master,
        &Debug__Top_slots[InstId_Debug__Top_Debug__Simulator_server1],
        1,
        &borderfarEndList_Debug__Top_Debug__Simulator_server1[2],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true
    },
    {
        &Server,
        Capsule_Server::borderport_MasterAnnounceTimer,
        &Debug__Top_slots[InstId_Debug__Top_Debug__Simulator_server1],
        1,
        &borderfarEndList_Debug__Top_Debug__Simulator_server1[3],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false
    },
    {
        &Server,
        Capsule_Server::borderport_ServerComm,
        &Debug__Top_slots[InstId_Debug__Top_Debug__Simulator_server1],
        5,
        &borderfarEndList_Debug__Top_Debug__Simulator_server1[4],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true
    },
    {
        &Server,
        Capsule_Server::borderport_Slave,
        &Debug__Top_slots[InstId_Debug__Top_Debug__Simulator_server1],
        1,
        &borderfarEndList_Debug__Top_Debug__Simulator_server1[9],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true
    },
    {
        &Server,
        Capsule_Server::borderport_Timer,
        &Debug__Top_slots[InstId_Debug__Top_Debug__Simulator_server1],
        1,
        &borderfarEndList_Debug__Top_Debug__Simulator_server1[10],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false
    },
    {
        &Server,
        Capsule_Server::borderport_extComm,
        &Debug__Top_slots[InstId_Debug__Top_Debug__Simulator_server1],
        1,
        &borderfarEndList_Debug__Top_Debug__Simulator_server1[11],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        true,
        false,
        false,
        true,
        false,
        false,
        false
    }
};

static const UMLRTCommsPort * borderports_Debug__Top_Debug__Simulator_server1_ptrs[] = 
{
    &borderports_Debug__Top_Debug__Simulator_server1[0],
    &borderports_Debug__Top_Debug__Simulator_server1[1],
    &borderports_Debug__Top_Debug__Simulator_server1[2],
    &borderports_Debug__Top_Debug__Simulator_server1[3],
    &borderports_Debug__Top_Debug__Simulator_server1[4],
    &borderports_Debug__Top_Debug__Simulator_server1[5],
    &borderports_Debug__Top_Debug__Simulator_server1[6],
    &borderports_Debug__Top_Debug__Simulator_server1[7]
};

static Capsule_Server debug__Top_Debug__Simulator_server1( &Server, &Debug__Top_slots[InstId_Debug__Top_Debug__Simulator_server1], borderports_Debug__Top_Debug__Simulator_server1_ptrs, NULL, true );

static UMLRTCommsPortFarEnd borderfarEndList_Debug__Top_Debug__Simulator_server2[] = 
{
    {
        0,
        NULL
    },
    {
        0,
        NULL
    },
    {
        0,
        &borderports_Debug__Top_Debug__Simulator_server1[Capsule_Server::borderport_Slave]
    },
    {
        0,
        NULL
    },
    {
        0,
        &borderports_Debug__Top_Debug__Simulator_client_0[Capsule_Client::borderport_Server2Comm]
    },
    {
        0,
        &borderports_Debug__Top_Debug__Simulator_client_1[Capsule_Client::borderport_Server2Comm]
    },
    {
        0,
        &borderports_Debug__Top_Debug__Simulator_client_2[Capsule_Client::borderport_Server2Comm]
    },
    {
        0,
        &borderports_Debug__Top_Debug__Simulator_client_3[Capsule_Client::borderport_Server2Comm]
    },
    {
        0,
        &borderports_Debug__Top_Debug__Simulator_client_4[Capsule_Client::borderport_Server2Comm]
    },
    {
        0,
        &borderports_Debug__Top_Debug__Simulator_server1[Capsule_Server::borderport_Master]
    },
    {
        0,
        NULL
    },
    {
        0,
        NULL
    }
};

UMLRTCommsPort borderports_Debug__Top_Debug__Simulator_server2[] = 
{
    {
        &Server,
        Capsule_Server::borderport_ConfigComm,
        &Debug__Top_slots[InstId_Debug__Top_Debug__Simulator_server2],
        1,
        borderfarEndList_Debug__Top_Debug__Simulator_server2,
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false
    },
    {
        &Server,
        Capsule_Server::borderport_KeepAliveTimer,
        &Debug__Top_slots[InstId_Debug__Top_Debug__Simulator_server2],
        1,
        &borderfarEndList_Debug__Top_Debug__Simulator_server2[1],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false
    },
    {
        &Server,
        Capsule_Server::borderport_Master,
        &Debug__Top_slots[InstId_Debug__Top_Debug__Simulator_server2],
        1,
        &borderfarEndList_Debug__Top_Debug__Simulator_server2[2],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true
    },
    {
        &Server,
        Capsule_Server::borderport_MasterAnnounceTimer,
        &Debug__Top_slots[InstId_Debug__Top_Debug__Simulator_server2],
        1,
        &borderfarEndList_Debug__Top_Debug__Simulator_server2[3],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false
    },
    {
        &Server,
        Capsule_Server::borderport_ServerComm,
        &Debug__Top_slots[InstId_Debug__Top_Debug__Simulator_server2],
        5,
        &borderfarEndList_Debug__Top_Debug__Simulator_server2[4],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true
    },
    {
        &Server,
        Capsule_Server::borderport_Slave,
        &Debug__Top_slots[InstId_Debug__Top_Debug__Simulator_server2],
        1,
        &borderfarEndList_Debug__Top_Debug__Simulator_server2[9],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        false,
        false,
        false,
        true
    },
    {
        &Server,
        Capsule_Server::borderport_Timer,
        &Debug__Top_slots[InstId_Debug__Top_Debug__Simulator_server2],
        1,
        &borderfarEndList_Debug__Top_Debug__Simulator_server2[10],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        false,
        false,
        false,
        true,
        false,
        false,
        false
    },
    {
        &Server,
        Capsule_Server::borderport_extComm,
        &Debug__Top_slots[InstId_Debug__Top_Debug__Simulator_server2],
        1,
        &borderfarEndList_Debug__Top_Debug__Simulator_server2[11],
        NULL,
        NULL,
        "",
        true,
        true,
        true,
        false,
        true,
        false,
        false,
        true,
        false,
        false,
        false
    }
};

static const UMLRTCommsPort * borderports_Debug__Top_Debug__Simulator_server2_ptrs[] = 
{
    &borderports_Debug__Top_Debug__Simulator_server2[0],
    &borderports_Debug__Top_Debug__Simulator_server2[1],
    &borderports_Debug__Top_Debug__Simulator_server2[2],
    &borderports_Debug__Top_Debug__Simulator_server2[3],
    &borderports_Debug__Top_Debug__Simulator_server2[4],
    &borderports_Debug__Top_Debug__Simulator_server2[5],
    &borderports_Debug__Top_Debug__Simulator_server2[6],
    &borderports_Debug__Top_Debug__Simulator_server2[7]
};

static Capsule_Server debug__Top_Debug__Simulator_server2( &Server, &Debug__Top_slots[InstId_Debug__Top_Debug__Simulator_server2], borderports_Debug__Top_Debug__Simulator_server2_ptrs, NULL, true );

UMLRTSlot Debug__Top_slots[] = 
{
    {
        "Debug__Top",
        0,
        &Debug__Top,
        NULL,
        0,
        &debug__Top,
        &DefaultController_,
        2,
        parts_Debug__Top,
        0,
        NULL,
        NULL,
        true,
        false
    },
    {
        "Debug__Top.Debug__Gateway",
        0,
        &GateWay,
        &Debug__Top,
        Capsule_Debug__Top::part_Debug__Gateway,
        &debug__Top_Debug__Gateway,
        &DefaultController_,
        0,
        NULL,
        3,
        borderports_Debug__Top_Debug__Gateway,
        NULL,
        true,
        false
    },
    {
        "Debug__Top.Debug__Simulator",
        0,
        &Simulator,
        &Debug__Top,
        Capsule_Debug__Top::part_Debug__Simulator,
        &debug__Top_Debug__Simulator,
        &DefaultController_,
        4,
        parts_Debug__Top_Debug__Simulator,
        0,
        NULL,
        NULL,
        true,
        false
    },
    {
        "Debug__Top.Debug__Simulator.ENV",
        0,
        &ENV,
        &Simulator,
        Capsule_Simulator::part_ENV,
        &debug__Top_Debug__Simulator_ENV,
        &DefaultController_,
        0,
        NULL,
        8,
        borderports_Debug__Top_Debug__Simulator_ENV,
        NULL,
        true,
        false
    },
    {
        "Debug__Top.Debug__Simulator.client[0]",
        0,
        &Client,
        &Simulator,
        Capsule_Simulator::part_client,
        &debug__Top_Debug__Simulator_client_0,
        &DefaultController_,
        0,
        NULL,
        8,
        borderports_Debug__Top_Debug__Simulator_client_0,
        NULL,
        true,
        false
    },
    {
        "Debug__Top.Debug__Simulator.client[1]",
        1,
        &Client,
        &Simulator,
        Capsule_Simulator::part_client,
        &debug__Top_Debug__Simulator_client_1,
        &DefaultController_,
        0,
        NULL,
        8,
        borderports_Debug__Top_Debug__Simulator_client_1,
        NULL,
        true,
        false
    },
    {
        "Debug__Top.Debug__Simulator.client[2]",
        2,
        &Client,
        &Simulator,
        Capsule_Simulator::part_client,
        &debug__Top_Debug__Simulator_client_2,
        &DefaultController_,
        0,
        NULL,
        8,
        borderports_Debug__Top_Debug__Simulator_client_2,
        NULL,
        true,
        false
    },
    {
        "Debug__Top.Debug__Simulator.client[3]",
        3,
        &Client,
        &Simulator,
        Capsule_Simulator::part_client,
        &debug__Top_Debug__Simulator_client_3,
        &DefaultController_,
        0,
        NULL,
        8,
        borderports_Debug__Top_Debug__Simulator_client_3,
        NULL,
        true,
        false
    },
    {
        "Debug__Top.Debug__Simulator.client[4]",
        4,
        &Client,
        &Simulator,
        Capsule_Simulator::part_client,
        &debug__Top_Debug__Simulator_client_4,
        &DefaultController_,
        0,
        NULL,
        8,
        borderports_Debug__Top_Debug__Simulator_client_4,
        NULL,
        true,
        false
    },
    {
        "Debug__Top.Debug__Simulator.server1",
        0,
        &Server,
        &Simulator,
        Capsule_Simulator::part_server1,
        &debug__Top_Debug__Simulator_server1,
        &DefaultController_,
        0,
        NULL,
        8,
        borderports_Debug__Top_Debug__Simulator_server1,
        NULL,
        true,
        false
    },
    {
        "Debug__Top.Debug__Simulator.server2",
        0,
        &Server,
        &Simulator,
        Capsule_Simulator::part_server2,
        &debug__Top_Debug__Simulator_server2,
        &DefaultController_,
        0,
        NULL,
        8,
        borderports_Debug__Top_Debug__Simulator_server2,
        NULL,
        true,
        false
    }
};

