##################################################
# Default makefile
# Redirect make to target makefile
##################################################

all:
	make -f MakefileDebug__Top.mk all
clean:
	make -f MakefileDebug__Top.mk clean
.PHONY: 
	make -f MakefileDebug__Top.mk all clean
