##################################################
# Default makefile
# Redirect make to target makefile
##################################################

all:
	make -f MakefileCounter.mk all
clean:
	make -f MakefileCounter.mk clean
.PHONY: 
	make -f MakefileCounter.mk all clean
