##################################################
# Default makefile
# Redirect make to target makefile
##################################################

all:
	make -f MakefileParcer_Router.mk all
clean:
	make -f MakefileParcer_Router.mk clean
.PHONY: 
	make -f MakefileParcer_Router.mk all clean
